// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions (
    apiKey: dotenv.env['webApiKey'] ?? "webApiKey not found",
    appId: dotenv.env['WebAppId'] ?? "WebAppId not found",
    messagingSenderId: dotenv.env['messagingSenderId'] ?? "messagingSenderId not found",
    projectId: dotenv.env['projectId'] ?? "projectId not found",
    authDomain: dotenv.env['authDomain'] ?? "authDomain not found",
    storageBucket: dotenv.env['storageBucket'] ?? "storageBucket not found",
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['androidApiKey'] ?? "androidApiKey not found",
    appId: dotenv.env['androidAppId'] ?? "androidAppId not found",
    messagingSenderId: dotenv.env['messagingSenderId'] ?? "messagingSenderId not found",
    projectId: dotenv.env['projectId'] ?? "projectId not found",
    storageBucket: dotenv.env['storageBucket'] ?? "storageBucket not found",
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['osApiKey'] ?? "osApiKey not found",
    appId: dotenv.env['iosAppId'] ?? "iosAppId not found",
    messagingSenderId: dotenv.env['messagingSenderId'] ?? "messagingSenderId not found",
    projectId: dotenv.env['projectId'] ?? "projectId not found",
    storageBucket: dotenv.env['storageBucket'] ?? "storageBucket not found",
    iosClientId: dotenv.env['iosClientId'] ?? "iosClientId not found",
    iosBundleId: dotenv.env['iosBundleId'] ?? "iosBundleId not found",
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['iosBundleId'] ?? "macosApiKey not found",
    appId: dotenv.env['macosAppId'] ?? "macosAppId not found",
    messagingSenderId: dotenv.env['iosBundleId'] ?? "iosBundleId not found",
    projectId: dotenv.env['projectId'] ?? "projectId not found",
    storageBucket: dotenv.env['storageBucket'] ?? "storageBucket not found",
    iosClientId: dotenv.env['iosClientId'] ?? "iosClientId not found",
    iosBundleId: dotenv.env['iosBundleId'] ?? "iosBundleId not found",
  );
}
